# 00_open_and_inspect_svg

First step in a workflow for translating SVG text with an LLM:

- open SVG files from `svg_source_files`
- extract and inspect SVG `<text>` elements and their nested `<tspan>` fragments
- preserve meaningful whitespace from the SVG, including space-only tspans
- recombine fragmented tspans into text-level translation units
- exclude items not intended for translation, such as numeric-only labels and timeline/date markers
- save translation units as JSON in `json_files` for the next notebook, `01_translate_svg`

In [1]:
# Set directories

from pathlib import Path

PROJECT_ROOT = Path.cwd()
SVG_SOURCE_DIR = PROJECT_ROOT / "svg_source_files"
SVG_OUTPUT_DIR = PROJECT_ROOT / "svg_output_files"
JSON_DIR = PROJECT_ROOT / "json_files"

# Source/input folder should already exist
assert SVG_SOURCE_DIR.exists(), f"Missing folder: {SVG_SOURCE_DIR}"

# Output folders can be created automatically
SVG_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
JSON_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT.name)
print("SVG_SOURCE_DIR:", SVG_SOURCE_DIR.relative_to(PROJECT_ROOT.parent))
print("JSON_DIR:", JSON_DIR.relative_to(PROJECT_ROOT.parent))
print("SVG_OUTPUT_DIR:", SVG_OUTPUT_DIR.relative_to(PROJECT_ROOT.parent))

PROJECT_ROOT: tbe
SVG_SOURCE_DIR: tbe\svg_source_files
JSON_DIR: tbe\json_files
SVG_OUTPUT_DIR: tbe\svg_output_files

In [2]:
# Display svg files in source directory

svg_paths = sorted(SVG_SOURCE_DIR.glob("*.svg"))

print("Found SVG files:", len(svg_paths))
for p in svg_paths:
    print(" -", p.name)

Found SVG files: 4
 - tbe_01.svg
 - tbe_02.svg
 - tbe_03.svg
 - tbe_04.svg

## Read and parse SVG files
**NOTE:** This workflow will process *all* svg files contained in the svg_source_files directory

In [3]:
from lxml import etree
import pandas as pd
import json
import re

SVG_NS = "http://www.w3.org/2000/svg"
NS = {"svg": SVG_NS}

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag and tag.startswith("{") else (tag or "")

def norm_ws(s: str) -> str:
    if s is None:
        return ""
    return re.sub(r"\s+", " ", s).strip()

def parse_style(style: str):
    out = {}
    if not style:
        return out
    for part in style.split(";"):
        part = part.strip()
        if not part or ":" not in part:
            continue
        k, v = part.split(":", 1)
        out[k.strip()] = v.strip()
    return out

def group_label(g) -> str:
    return g.get("data-name") or g.get("id") or "g"

def compute_group_stack(el) -> list[str]:
    stack = []
    cur = el.getparent()
    while cur is not None:
        if localname(cur.tag) == "g":
            stack.append(group_label(cur))
        cur = cur.getparent()
    return list(reversed(stack))

def element_path(el) -> str:
    parts = []
    cur = el
    while cur is not None:
        tag = localname(cur.tag)
        if tag in ("svg", "g", "text", "tspan"):
            _id = cur.get("id")
            if _id:
                parts.append(f"{tag}#{_id}")
            else:
                parent = cur.getparent()
                if parent is None:
                    parts.append(tag)
                else:
                    same = [
                        c for c in parent
                        if hasattr(c, "tag") and localname(c.tag) == tag
                    ]
                    idx = same.index(cur) + 1  # 1-based index
                    parts.append(f"{tag}[{idx}]")
        cur = cur.getparent()
    return "/".join(reversed(parts))

def get_text_and_tspans(text_el):
    tspans = []
    chunks = []
    if text_el.text not in (None, ""):
        chunks.append(text_el.text)

    for t in text_el.findall(".//svg:tspan", namespaces=NS):
        t_text = t.text or ""
        if t_text != "":
            chunks.append(t_text)
        tspans.append({
            "tspan_id": t.get("id"),
            "tspan_text": t_text,
            "tspan_text_norm": norm_ws(t_text),
            "x": t.get("x"),
            "y": t.get("y"),
            "dx": t.get("dx"),
            "dy": t.get("dy"),
            "style": t.get("style"),
            "class": t.get("class"),
        })
        if t.tail not in (None, ""):
            chunks.append(t.tail)

    return "".join(chunks), tspans

def extract_text_inventory(svg_path: Path) -> pd.DataFrame:
    parser = etree.XMLParser(remove_blank_text=False, recover=True, huge_tree=True)
    tree = etree.parse(str(svg_path), parser)
    root = tree.getroot()

    rows = []
    for text_el in root.xpath("//svg:text", namespaces=NS):
        full_text, tspans = get_text_and_tspans(text_el)
        full_text_norm = norm_ws(full_text)
        if not full_text_norm:
            continue

        gstack = compute_group_stack(text_el)
        style = parse_style(text_el.get("style"))

        rows.append({
            "source_file": svg_path.name,
            "text_id": text_el.get("id"),
            "group_stack": " / ".join(gstack),
            "group_depth": len(gstack),
            "text_raw": full_text,
            "text_norm": full_text_norm,
            "has_tspans": len(tspans) > 0,
            "tspan_count": len(tspans),
            "x": text_el.get("x"),
            "y": text_el.get("y"),
            "transform": text_el.get("transform"),
            "class": text_el.get("class"),
            "style": text_el.get("style"),
            "style_font_family": style.get("font-family"),
            "style_font_size": style.get("font-size"),
            "style_text_anchor": style.get("text-anchor"),
            "element_path": element_path(text_el),
            "tspans": tspans,
        })

    df = pd.DataFrame(rows).sort_values(["group_stack", "element_path"]).reset_index(drop=True)
    return df

all_dfs = []
for p in svg_paths:
    df = extract_text_inventory(p)
    all_dfs.append(df)

    out_json = JSON_DIR / f"{p.stem}.text_extract.json"
    records = df.to_dict(orient="records")
    out_json.write_text(json.dumps(records, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"{p.name}: extracted {len(df)} text elements -> {out_json.name}")

df_all = pd.concat(all_dfs, ignore_index=True) if all_dfs else pd.DataFrame()
print("Total extracted across files:", len(df_all))

missing_space_pattern_rows = df_all[df_all["text_norm"].str.contains(r"[a-z][A-Z]", regex=True, na=False)]
print("Likely missing-space pattern rows:", len(missing_space_pattern_rows))
missing_space_pattern_rows[["text_raw", "text_norm", "group_stack", "element_path"]]

tbe_01.svg: extracted 40 text elements -> tbe_01.text_extract.json
tbe_02.svg: extracted 104 text elements -> tbe_02.text_extract.json
tbe_03.svg: extracted 136 text elements -> tbe_03.text_extract.json
tbe_04.svg: extracted 104 text elements -> tbe_04.text_extract.json
Total extracted across files: 384
Likely missing-space pattern rows: 0

Empty DataFrame
Columns: [text_raw, text_norm, group_stack, element_path]
Index: []

### Human-readable summary

In [4]:
def outline(df: pd.DataFrame, max_chars: int = 90):
    for i, r in df.iterrows():
        snippet = r["text_norm"]
        if len(snippet) > max_chars:
            snippet = snippet[:max_chars-1] + "…"
        print(f"[{i:04d}] {r['group_stack']} :: {snippet}")

for fname in df_all["source_file"].unique():
    print("\n" + "="*80)
    print(fname)
    print("="*80)
    outline(df_all[df_all["source_file"] == fname].reset_index(drop=True), max_chars=110)

================================================================================
tbe_01.svg
================================================================================
[0000] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Adam :: d. 3244
[0001] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Adam :: Adam 4174
[0002] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Enoch :: 3187
[0003] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Enoch :: Enoch 3552
[0004] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Enosh :: d. 3034
[0005] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Enosh :: Enosh 3939
[0006] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Jared :: Jared 3714
[0007] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Kenan :: d. 2939
[0008] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Kenan :: Kenan 3849
[0009] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Lamech :: Lamech 3300
[0010] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Mahalalel :: d. 2884
[0011] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Mahalalel :: Mahalalel 3779
[0012] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Methuselah :: Methuselah 3487
[0013] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Noah :: Noah 3118
[0014] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Seth :: d. 3132
[0015] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_patriarchs / Seth :: Seth 4044
[0016] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_text / ab1_x5F_biblical_x5F_text_x5F_booknames :: Genesis
[0017] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_text / ab1_x5F_biblical_x5F_text_x5F_epoch :: 3. Pre-Flood (ch v 3-5)
[0018] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_text / ab1_x5F_biblical_x5F_text_x5F_epoch :: 2. Edenic (ch 2)
[0019] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_text / ab1_x5F_biblical_x5F_text_x5F_epoch :: 1. Creation (ch 1)
[0020] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_text / ab1_x5F_biblical_x5F_text_x5F_epoch :: Epoch:
[0021] AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_text / ab1_x5F_biblical_x5F_text_x5F_scripture :: Enoch walked with God, and he was not found, for God took him. Gen 5:24
[0022] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_China :: China
[0023] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_China :: Period of Three Sovereigns and Five Emperors ca 2850
[0024] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_Egypt :: Egypt
[0025] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_Egypt :: Ancient Egyptian civilization ca 3100
[0026] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_Egypt :: Old Kingdom
[0027] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_Greco-Roman :: Greco-Roman
[0028] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_Greco-Roman :: Helladic (Greece) and Minoan civilation (Crete) ca 2800
[0029] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_India :: India
[0030] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_India :: Start of Indus Valley civilization ca 3000
[0031] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_Mesopotamia :: Mesopotamia
[0032] AB1 / ab1_x5F_empire_x5F_text / ab1_x5F_Mesopotamia :: Rise of Mesopotamian civilization ca 3400
[0033] AB1 / ab1_x5F_scale / ab1_x5F_scale_x5F_numeric :: 4000
[0034] AB1 / ab1_x5F_scale / ab1_x5F_scale_x5F_numeric :: 3500
[0035] AB1 / ab1_x5F_scale / ab1_x5F_scale_x5F_numeric :: 3000
[0036] AB1 / ab1_x5F_scale / ab1_x5F_scale_x5F_text :: Age of the Patriarchs
[0037] AB1 / ab1_x5F_scale / ab1_x5F_scale_x5F_text :: dates on this page are approximate and difficult to verify
[0038] AB1 / ab1_x5F_title :: Prehistory to 2800 bc
[0039] AB1 / ab1_x5F_title :: Timeline of Biblical Events in Perspective of World History

================================================================================
tbe_02.svg
================================================================================
[0000] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs :: Ismael 2080
[0001] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Abraham :: d. 1991
[0002] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Abraham :: Abraham 2166
[0003] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Arphaxad :: d. 2078
[0004] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Arphaxad :: Arphaxad 2516
[0005] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Eber :: d. 1987
[0006] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Eber :: Eber 2451
[0007] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Hebrew :: possible origin of ‘Hebrew’
[0008] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Isaac :: d. 1886
[0009] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Isaac :: Isaac 2066
[0010] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Jacob :: d. 1859
[0011] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Jacob :: Jacob 2006*
[0012] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Jared2 :: Jared d. 2752
[0013] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Lamech2 :: Lamech d. 2523
[0014] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Methuselah2 :: Methuselahd. 2518
[0015] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Nahor :: d. 2177
[0016] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Nahor :: Nahor 2325
[0017] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Noah2 :: Noah d. 2170
[0018] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Peleg :: d. 2178
[0019] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Peleg :: Peleg 2417
[0020] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Reu :: d. 2148
[0021] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Reu :: Reu 2387
[0022] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Serug :: d. 2125
[0023] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Serug :: Serug 2355
[0024] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Shelah :: d. 2048
[0025] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Shelah :: Shelah 2481
[0026] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Shem :: d. 2016
[0027] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Shem :: Shem 2616
[0028] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Terah :: d. 2091
[0029] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_patriarchs / Terah :: Terah 2296
[0030] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_booknames :: not date of writing
[0031] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_booknames :: period of story
[0032] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_booknames :: Job
[0033] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_booknames :: Exodus
[0034] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_booknames :: Genesis
[0035] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_epoch :: 6. Current (Gen 12 – Rev 20)
[0036] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_epoch :: 5. Post-flood to Babel (ch 9-11)
[0037] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_epoch :: 4. Flood (ch 6-8)
[0038] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_epoch :: Epoch:
[0039] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Flood ca 2520-19
[0040] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Starting with an extra-biblical date of 966 bc for the fourthyear of Solomon’s reign, Exodus is backdated to …
[0041] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: *Back-calculation method:
[0042] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Moses born 1526
[0043] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Moses flees to Midian 1486
[0044] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Exodus from Egypt 1446*
[0045] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Abraham enters Promised Land 2091
[0046] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Sodom and Gomorrah destroyed
[0047] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Joseph sold into slavery 1898
[0048] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Jacob enters Egypt 1876*
[0049] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Joseph becomes ruler in Egypt 1886
[0050] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_events :: Tower of Babel (uncertain)
[0051] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Asher
[0052] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Gad
[0053] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Naphtali
[0054] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Dan
[0055] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Judah
[0056] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Levi
[0057] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Simeon
[0058] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Reuben
[0059] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Leah
[0060] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Zilpah
[0061] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Rachel
[0062] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Bilhah
[0063] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: d. 1806
[0064] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Joseph 1916
[0065] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Benjamin
[0066] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Zebulun (and Dinah)
[0067] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_jacobschildren :: Issachar
[0068] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_scripture :: Now the time that the children of Israel lived in Egypt was four hundred thirty years. Exodus 12:40
[0069] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_scripture :: Now there arose a new king over Egypt,who didn’t know Joseph. Exodus 1:8
[0070] AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_text / ab2_x5F_biblical_x5F_text_x5F_scripture :: for in his days the Earth was divided Genesis 10:25
[0071] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_China :: China
[0072] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_China :: Xia Dynasty ca 2070
[0073] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_China :: Xia Dynasty
[0074] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_China :: Shang Dynasty ca 1600
[0075] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_China :: Three Sovereigns and Five Emperors
[0076] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Egypt :: Egypt
[0077] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Egypt :: Sesostris III 12th Dynasty ca 1878
[0078] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Egypt :: Hyksos invasion begins ca 1650
[0079] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Egypt :: Hyksos driven out 1570
[0080] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Egypt :: Middle Kingdom Period
[0081] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Egypt :: Ancient Egyptian civilization
[0082] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Greco-Roman :: Greco-Roman
[0083] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Greco-Roman :: Mycanaean period (Greece) ca 1600
[0084] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Greco-Roman :: Helladic and Minoan civilation
[0085] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_India :: India
[0086] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_India :: Late Harappan ca 1700
[0087] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_India :: Vedic Period ca 1500
[0088] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_India :: Indus Valley civilization
[0089] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Mesopotamia :: Mesopotamia
[0090] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Mesopotamia :: Akkadian Empire ca 2330
[0091] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Mesopotamia :: Hammurabi ca 1792
[0092] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Mesopotamia :: First Babylonian Dynasty
[0093] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Mesopotamia :: Mesopotamian civilization
[0094] AB2 / ab2_x5F_empire_x5F_text / ab2_x5F_Mesopotamia :: Middle Assyrian Period
[0095] AB2 / ab2_x5F_scale / ab2_x5F_scale_x5F_numeric :: 2500
[0096] AB2 / ab2_x5F_scale / ab2_x5F_scale_x5F_numeric :: 2000
[0097] AB2 / ab2_x5F_scale / ab2_x5F_scale_x5F_numeric :: 1500
[0098] AB2 / ab2_x5F_scale / ab2_x5F_scale_x5F_text :: Abraham to Joseph
[0099] AB2 / ab2_x5F_scale / ab2_x5F_scale_x5F_text :: Age of the Patriarchs
[0100] AB2 / ab2_x5F_scale / ab2_x5F_scale_x5F_text :: 400 Years of Slavery
[0101] AB2 / ab2_x5F_scale / ab2_x5F_scale_x5F_text :: dates on this page are approximate and difficult to verify
[0102] AB2 / ab2_x5F_title :: 2800 to 1400 bc
[0103] AB2 / ab2_x5F_title :: Timeline of Biblical Events in Perspective of World History

================================================================================
tbe_03.svg
================================================================================
[0000] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text :: Poetical
[0001] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text :: Prophetic
[0002] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames :: Ezra Est Ezra Neh
[0003] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames :: Exile
[0004] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames :: 1-2 Kings / 2 Chronicles
[0005] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames :: 1-2 Sam1 Chron
[0006] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames :: Judges
[0007] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames :: Ruth
[0008] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames :: Joshua
[0009] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames :: Lev-Dt
[0010] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_edom :: Obadiah
[0011] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_edom :: < prophet to Edom
[0012] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_poetry :: Psalms
[0013] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_poetry :: Song of Solomon
[0014] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_poetry :: Proverbs
[0015] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_poetry :: Ecclesiastes
[0016] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstoassyria :: Nahum
[0017] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstoassyria :: Jonah
[0018] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstoassyria :: prophets to Assyria
[0019] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstoisrael :: Hosea
[0020] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstoisrael :: Amos
[0021] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstoisrael :: prophets to Israel
[0022] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstojudah_00000150820972040878145210000015563713028438143625_ :: Isaiah
[0023] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstojudah_00000150820972040878145210000015563713028438143625_ :: Habakkuk
[0024] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstojudah_00000150820972040878145210000015563713028438143625_ :: prophets to Judah
[0025] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstojudah_00000150820972040878145210000015563713028438143625_ :: Malachi
[0026] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstojudah_00000150820972040878145210000015563713028438143625_ :: Zechariah
[0027] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstojudah_00000150820972040878145210000015563713028438143625_ :: Haggai
[0028] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstojudah_00000150820972040878145210000015563713028438143625_ :: Daniel
[0029] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstojudah_00000150820972040878145210000015563713028438143625_ :: Ezekiel
[0030] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstojudah_00000150820972040878145210000015563713028438143625_ :: Zephaniah
[0031] AB3 / ab3_x5F_biblical / ab3_x5F_biblical_x5F_text / ab3_x5F_biblical_x5F_text_x5F_booknames / ab3_x5F_biblical_x5F_text_x5F_booknames_x5F_prophetstojudah_00000150820972040878145210000015563713028438143625_ :: Micah

### Create LLM-ready table of elements

In [5]:
import hashlib
import pandas as pd

def make_unit_key(source_file: str, element_path: str, text_id: str | None, source_text: str) -> str:
    # Hash stable text-level information.
    parts = [source_file, element_path]
    if text_id is not None and not pd.isna(text_id) and str(text_id).strip():
        parts.append(f"text_id={text_id}")
    parts.append(f"source_text={source_text}")
    raw = "|".join(parts)
    return hashlib.sha1(raw.encode("utf-8")).hexdigest()

def nonempty_text(value) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).strip()

def build_translation_df(df_text: pd.DataFrame) -> pd.DataFrame:
    out = []
    for _, r in df_text.iterrows():
        source_file = r["source_file"]
        element_path = r["element_path"]
        group_stack = r["group_stack"]
        text_id = r.get("text_id")

        src = nonempty_text(r.get("text_norm"))
        if not src:
            tspans = r.get("tspans")
            if not isinstance(tspans, list):
                tspans = []
            src = "".join(nonempty_text(t.get("tspan_text_norm")) for t in tspans)
            src = " ".join(src.split())

        if not src:
            continue

        unit_key = make_unit_key(source_file, element_path, text_id, src)
        out.append({
            "unit_key": unit_key,
            "unit_type": "text",
            "source_file": source_file,
            "group_stack": group_stack,
            "element_path": element_path,
            "text_id": text_id,
            "tspan_id": None,
            "tspan_idx": None,
            "source_text": src,
        })

    columns = ["unit_key", "unit_type", "source_file", "group_stack", "element_path", "text_id", "tspan_id", "tspan_idx", "source_text"]
    df_units = pd.DataFrame(out, columns=columns)
    # helpful sorting for review
    return df_units.sort_values(["source_file", "group_stack", "element_path", "unit_type", "tspan_idx"]).reset_index(drop=True)

df_units = build_translation_df(df_all)
print("Total translation units:", len(df_units))
print("Rows containing Adam:", df_units["source_text"].str.contains("Adam", na=False).sum())
print("First 20 rows of df_units:")
df_units.head(20)

Total translation units: 384
Rows containing Adam: 1
First 20 rows of df_units:

,unit_key,unit_type,source_file,group_stack,element_path,text_id,tspan_id,tspan_idx,source_text
0,191f152ec4069b81f0c6059d6374f8d6bfb3dc0c,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 3244
1,42415ca24611ff65186249ab11a15d368b1530d6,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Adam 4174
2,d36f6b0ba1629a6c63cba162cb0023e15b3b331d,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,3187
3,63b52a9dd6f89c753d7d5daf49710893a72629c7,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Enoch 3552
4,294d4a1c53b8e9c82bd7608fc412f7c1f5996ad3,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 3034
5,c7cbff308d158d2ed4d94d7294e625fc2a2319dc,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Enosh 3939
6,872ee56f45524087e305b6a4cdcd8d5a1fce1159,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Jared 3714
7,aaec140285126bea8a3d234be0142a830eb466b4,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 2939
8,e40bcebd3c831a8e80a629f41bf3e7104d2b251c,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Kenan 3849
9,3c23d44eb081747c7ba965be21bee62ddd2676b5,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Lamech 3300
10,2795cb668670d71350f64b40991e8f5652855f9a,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 2884
11,2c5b67b2cdc4c79daa161d826445b83c7b614c89,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Mahalalel 3779
12,7ee468a69144fb5233179d42fe06d7a69bdb3f57,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Methuselah 3487
13,1b1910bf74e9a176beec1ccbd18517c88b4db05c,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Noah 3118
14,138aac566f8ac14ed6d91a648eed5f6ded21af44,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 3132
15,1c1a27384f36d007b684cd5c61c9396394f7a395,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Seth 4044
16,f69f31b2dcd4223c3a217bb7754558fc3e3aec63,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Genesis
17,b1840eb1bf63aba1703903a3b9278597091e5fec,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,3. Pre-Flood (ch v 3-5)
18,2f008eb5fd9262507374c41e0cde755d5db2a9a0,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,2. Edenic (ch 2)
19,248d6bf7eb6599441da5e0723cf9e5e156f0b351,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,1. Creation (ch 1)

### Skip numbers and dates
Comment out if you wish to have the LLM translate the numbers or dates

In [6]:
import re

def is_numericish(s: str) -> bool:
    s = s.strip().lower()
    # numbers, punctuation, simple bc/ad, ca
    return bool(re.fullmatch(r"[0-9\s\.,:\-–—/()]*", s)) or bool(re.fullmatch(r"(ca\s*)?[0-9\s\.,\-–—/]+(bc|bce|ad|ce)?", s))

def is_short_label(s: str) -> bool:
    return len(s.strip()) <= 2

def is_death_date_marker(s: str) -> bool:
    return bool(re.fullmatch(r"d\.\s*\d+", str(s).strip(), flags=re.IGNORECASE))

df_units["skip_reason"] = ""
df_units.loc[df_units["source_text"].map(is_short_label), "skip_reason"] = "too_short"
df_units.loc[df_units["source_text"].map(is_numericish), "skip_reason"] = "numericish"
df_units.loc[df_units["source_text"].map(is_death_date_marker), "skip_reason"] = "death_date_marker"

df_units_keep = df_units[df_units["skip_reason"] == ""].copy()
df_units_skip = df_units[df_units["skip_reason"] != ""].copy()

print("Total units:", len(df_units))
print("Translate candidates:", len(df_units_keep))
print("Skipped units:", len(df_units_skip))
print("death_date_marker rows:", (df_units["skip_reason"] == "death_date_marker").sum())

df_units.loc[
    df_units["skip_reason"] == "death_date_marker",
    ["source_text", "skip_reason", "group_stack", "element_path"],
]

Total units: 384
Translate candidates: 341
Skipped units: 43
death_date_marker rows: 18

,source_text,skip_reason,group_stack,element_path
0,d. 3244,death_date_marker,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...
4,d. 3034,death_date_marker,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...
7,d. 2939,death_date_marker,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...
10,d. 2884,death_date_marker,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...
14,d. 3132,death_date_marker,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...
41,d. 1991,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
43,d. 2078,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
45,d. 1987,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
48,d. 1886,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
50,d. 1859,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
55,d. 2177,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
58,d. 2178,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
60,d. 2148,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
62,d. 2125,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
64,d. 2048,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
66,d. 2016,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
68,d. 2091,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...
103,d. 1806,death_date_marker,AB2 / ab2_x5F_biblical / ab2_x5F_biblical_x5F_...,svg/g#AB2/g#ab2_x5F_biblical/g#ab2_x5F_biblica...

In [7]:
print("Duplicate unit_keys:", df_units_keep["unit_key"].duplicated().sum())

Duplicate unit_keys: 0

### Parse to JSON and save to JSON files directory
**CAUTION:** this will overwrite any previously run/saved versions

In [8]:
import json
from pathlib import Path

out_units = JSON_DIR / "translation_units.json"

if out_units.exists():
    print("Overwriting existing file:", out_units.relative_to(PROJECT_ROOT.parent))
else:
    print("Creating new file:", out_units.relative_to(PROJECT_ROOT.parent))

chars_written = out_units.write_text(
    json.dumps(df_units_keep.to_dict(orient="records"), ensure_ascii=False, indent=2),
    encoding="utf-8"
)

print("Characters written:", chars_written)

Overwriting existing file: tbe\json_files\translation_units.json
Characters written: 167098

In [9]:
df_all.head(2)

,source_file,text_id,group_stack,group_depth,text_raw,text_norm,has_tspans,tspan_count,x,y,transform,class,style,style_font_family,style_font_size,style_text_anchor,element_path,tspans
0,tbe_01.svg,None,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,4,d. 3244,d. 3244,False,0,None,None,matrix(1 0 0 1 690.3776 182.9529),None,None,None,None,None,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,[]
1,tbe_01.svg,None,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,4,Adam 4174,Adam 4174,False,0,None,None,matrix(1 0 0 1 21.8434 191.8456),None,None,None,None,None,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,[]

In [10]:
df_units.head(4)

,unit_key,unit_type,source_file,group_stack,element_path,text_id,tspan_id,tspan_idx,source_text,skip_reason
0,191f152ec4069b81f0c6059d6374f8d6bfb3dc0c,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 3244,death_date_marker
1,42415ca24611ff65186249ab11a15d368b1530d6,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Adam 4174,
2,d36f6b0ba1629a6c63cba162cb0023e15b3b331d,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,3187,numericish
3,63b52a9dd6f89c753d7d5daf49710893a72629c7,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Enoch 3552,

In [11]:
cols = [
    "unit_type",
    "source_file",
    "group_stack",
    "element_path",
    "text_id",
    "tspan_id",
    "tspan_idx",
    "source_text",
    "skip_reason",
]

df_units.loc[0:3, cols]

,unit_type,source_file,group_stack,element_path,text_id,tspan_id,tspan_idx,source_text,skip_reason
0,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 3244,death_date_marker
1,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Adam 4174,
2,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,3187,numericish
3,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Enoch 3552,

In [12]:
df_units.loc[0:3, ["element_path", "tspan_idx", "source_text"]].to_string(index=False)

'                                                                  element_path tspan_idx source_text\n svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblical_x5F_patriarchs/g#Adam/text[1]      None     d. 3244\n svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblical_x5F_patriarchs/g#Adam/text[2]      None   Adam 4174\nsvg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblical_x5F_patriarchs/g#Enoch/text[1]      None        3187\nsvg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblical_x5F_patriarchs/g#Enoch/text[2]      None  Enoch 3552'

In [13]:
(
    df_units
    .sort_values(["source_file", "element_path", "tspan_idx"])
    .groupby(["source_file", "element_path"], dropna=False)["source_text"]
    .apply(lambda parts: "".join(str(x) for x in parts if str(x) != "nan"))
    .reset_index(name="combined_text")
    .head(20)
)

,source_file,element_path,combined_text
0,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,d. 3244
1,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Adam 4174
2,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,3187
3,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Enoch 3552
4,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,d. 3034
5,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Enosh 3939
6,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Jared 3714
7,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,d. 2939
8,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Kenan 3849
9,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Lamech 3300
10,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,d. 2884
11,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Mahalalel 3779
12,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Methuselah 3487
13,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Noah 3118
14,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,d. 3132
15,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Seth 4044
16,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,Genesis
17,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,3. Pre-Flood (ch v 3-5)
18,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,2. Edenic (ch 2)
19,tbe_01.svg,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,1. Creation (ch 1)

In [14]:
print("Total units:", len(df_units))
print("Translate candidates:", (df_units["skip_reason"] == "").sum())
print("Skipped units:", (df_units["skip_reason"] != "").sum())

df_units.head(20)

Total units: 384
Translate candidates: 341
Skipped units: 43

,unit_key,unit_type,source_file,group_stack,element_path,text_id,tspan_id,tspan_idx,source_text,skip_reason
0,191f152ec4069b81f0c6059d6374f8d6bfb3dc0c,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 3244,death_date_marker
1,42415ca24611ff65186249ab11a15d368b1530d6,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Adam 4174,
2,d36f6b0ba1629a6c63cba162cb0023e15b3b331d,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,3187,numericish
3,63b52a9dd6f89c753d7d5daf49710893a72629c7,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Enoch 3552,
4,294d4a1c53b8e9c82bd7608fc412f7c1f5996ad3,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 3034,death_date_marker
5,c7cbff308d158d2ed4d94d7294e625fc2a2319dc,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Enosh 3939,
6,872ee56f45524087e305b6a4cdcd8d5a1fce1159,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Jared 3714,
7,aaec140285126bea8a3d234be0142a830eb466b4,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 2939,death_date_marker
8,e40bcebd3c831a8e80a629f41bf3e7104d2b251c,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Kenan 3849,
9,3c23d44eb081747c7ba965be21bee62ddd2676b5,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Lamech 3300,
10,2795cb668670d71350f64b40991e8f5652855f9a,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 2884,death_date_marker
11,2c5b67b2cdc4c79daa161d826445b83c7b614c89,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Mahalalel 3779,
12,7ee468a69144fb5233179d42fe06d7a69bdb3f57,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Methuselah 3487,
13,1b1910bf74e9a176beec1ccbd18517c88b4db05c,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Noah 3118,
14,138aac566f8ac14ed6d91a648eed5f6ded21af44,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,d. 3132,death_date_marker
15,1c1a27384f36d007b684cd5c61c9396394f7a395,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Seth 4044,
16,f69f31b2dcd4223c3a217bb7754558fc3e3aec63,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,Genesis,
17,b1840eb1bf63aba1703903a3b9278597091e5fec,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,3. Pre-Flood (ch v 3-5),
18,2f008eb5fd9262507374c41e0cde755d5db2a9a0,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,2. Edenic (ch 2),
19,248d6bf7eb6599441da5e0723cf9e5e156f0b351,text,tbe_01.svg,AB1 / ab1_x5F_biblical / ab1_x5F_biblical_x5F_...,svg/g#AB1/g#ab1_x5F_biblical/g#ab1_x5F_biblica...,None,None,None,1. Creation (ch 1),